force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Registration_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date_Time__c</fullName>
    <label>Registration Date-Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Free_Places__c.field-meta.xml
<CustomField>
    <fullName>Free_Places__c</fullName>
    <formula>Max_Participants_Quantity__c  -  Participants__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Free Places</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Max_Participants_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Max_Participants_Quantity__c</fullName>
    <label>Max Participants Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Training_Course__c.field-meta.xml
<CustomField>
    <fullName>Training_Course__c</fullName>
    <label>Training Course</label>
    <referenceTo>Training_Course__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ParticipantsAdderController.cls
public with sharing class ParticipantsAdderController {
    
    @auraEnabled
    public static List<Training__c> getTrainings(){
        List<Training__c> trainings=[SELECT id, Name, Training_Course__r.Name, Max_Participants_Quantity__c, Free_Places__c FROM Training__c];
		                
        return trainings;
    }
    @AuraEnabled    
    public static Boolean insertParticipants(String trainingName, Integer amount){
        boolean canInsert;
        Training__c t =[SELECT id, Free_Places__c FROM Training__C WHERE Name=:trainingName Limit 1];
        if(t.Free_Places__c >= amount){
            List <Participant__c> participants = New List<Participant__c>();
            for(integer a=0; a<amount; a++){
                Participant__c p = new Participant__c();
                p.Registration_Date_Time__c = DateTime.now();
                p.Training__c = t.id;
                participants.add(p);
            }
            insert participants;
            canInsert=true;
        }
        else{
            canInsert=false;
        }
        return canInsert;                       
    }
    
}