force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>In Queue</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training</label>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CertificatesGeneratorController.cls
public with sharing class CertificatesGeneratorController {
    @auraEnabled
    public static void savePDFCertificate(id trainingId){        
        List<Participant__c> participants = [SELECT id FROM Participant__c WHERE Training__c = :trainingId AND Status__c = 'Registered'];
        
        for(Participant__c p : participants){
            PageReference pdfPage = Page.PDF_Certificate;
		    pdfPage.getParameters().put('Id', p.id);
            Blob pdfContent = pdfPage.getContent();
            
            //Create Document
            ContentVersion cv = new ContentVersion();
            cv.Title = 'Certificate';
            cv.PathOnClient = 'Certificate.pdf';
            cv.VersionData = pdfContent;
            cv.IsMajorVersion = true;
            insert cv;
 
            //Get Content Document Id
            Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
 
            //Create ContentDocumentLink 
            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = p.id;
            cdl.ContentDocumentId = conDocId;
            cdl.shareType = 'V';
            insert cdl;
        }    
    }

    @auraEnabled
    public static List<String> getParticipants(id trainingId){
        List<Participant__c> participants=[SELECT Id FROM Participant__c WHERE Training__c = :trainingId AND Status__c = 'Registered'];
		List <String> ids = new List<String>();
        for(Participant__c p : participants){
            ids.add('/apex/PDF_Certificate?id='+String.valueOf(p.id));
        }
        return ids;
    }

    @AuraEnabled
    public static List<String> getCountries(){
        List<String> countries = new List<String>();
        countries.add('USA');
        countries.add('India');
        return countries;
    }
}